/**
 * super_sessions — Project Memory Foundation for pi
 *
 * Three-tier architecture:
 * 1. Mechanical: /super_sessions → .md + HTML (zero LLM cost)
 * 2. Analysis: super_sessions_analyze tool → per-session topic extraction (cheap model)
 * 3. Synthesis: super_sessions_synthesize tool → cross-session blueprint (SOTA model)
 */

import type { ExtensionAPI, ExtensionCommandContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import * as fs from "node:fs";
import * as path from "node:path";
import { extractSessionFile, buildIndex, listSessions, type SessionMeta } from "./extraction";
import { generateSessionHtml, generateIndexHtml } from "./html-generator";

// ─── Constants ────────────────────────────────────────────────────────────────────

const INSIGHTS_DIR = "project_insights";
const SESSIONS_DIR = "sessions";
const HTML_DIR = "html";
const ANALYSES_DIR = "analyses";
const WISDOM_DIR = "wisdom";

// ─── Helpers ──────────────────────────────────────────────────────────────────────

function getInsightsRoot(cwd: string): string {
  return path.join(cwd, INSIGHTS_DIR);
}

function getSessionsDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), SESSIONS_DIR);
}

function getHtmlDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), HTML_DIR);
}

function getAnalysesDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), ANALYSES_DIR);
}

function getWisdomDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), WISDOM_DIR);
}

// ─── Mechanical Extraction Command ────────────────────────────────────────────────

async function runMechanicalExtraction(ctx: ExtensionCommandContext): Promise<{
  sessions: SessionMeta[];
  count: number;
}> {
  const cwd = ctx.cwd;

  // Discover sessions via filesystem
  const sessionInfos = listSessions(cwd);
  if (sessionInfos.length === 0) {
    ctx.ui.notify("No sessions found for this project.", "warning");
    return { sessions: [], count: 0 };
  }

  const sessionsDir = getSessionsDir(cwd);
  const htmlDir = getHtmlDir(cwd);

  // Ensure output directories
  fs.mkdirSync(sessionsDir, { recursive: true });
  fs.mkdirSync(htmlDir, { recursive: true });

  const sessions: SessionMeta[] = [];
  let extracted = 0;
  let failed = 0;

  ctx.ui.notify(`Found ${sessionInfos.length} sessions. Extracting...`, "info");

  for (const info of sessionInfos) {
    try {
      const meta = extractSessionFile(info.path, sessionsDir, info);
      if (meta) {
        sessions.push(meta);
        generateSessionHtml(info.path, meta, htmlDir);
        extracted++;
      } else {
        failed++;
      }
    } catch {
      failed++;
    }
  }

  // Build index
  if (sessions.length > 0) {
    buildIndex(sessions, getInsightsRoot(cwd));
    generateIndexHtml(sessions, htmlDir);
  }

  // Write README once
  const readmePath = path.join(getInsightsRoot(cwd), "README.md");
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(readmePath, README_CONTENT, "utf-8");
  }

  ctx.ui.notify(
    `✅ Generated ${extracted} session exports to ${INSIGHTS_DIR}/ (${failed} failed)`,
    "success",
  );

  return { sessions, count: extracted };
}

// ─── README Template ─────────────────────────────────────────────────────────────

const README_CONTENT = `# Project Insights

Generated by **super_sessions** — a project memory foundation for pi.

## Directory Layout

\`\`\`
project_insights/
├── README.md          ← this file
├── index.md           ← session manifest (dates, counts, names)
├── sessions/          ← canonical source of truth
│   ├── YYYY-MM-DD_id.md       ← clean (user + assistant text)
│   └── YYYY-MM-DD_id_full.md  ← full (includes thinking, tool calls)
├── html/              ← visual browser (open index.html)
├── analyses/          ← per-session LLM extractions (by topic)
└── wisdom/            ← cross-session synthesis blueprints
\`\`\`

## How to Use

1. **Browse sessions** — Open \`html/index.html\` in any browser. No server required.
2. **Analyze by topic** — Have your agent run \`super_sessions_analyze\` with a topic.
3. **Synthesize wisdom** — Have your agent run \`super_sessions_synthesize\` to build blueprints.

## Commands & Tools

| Command/Tool | What it does |
|-------------|-------------|
| \`/super_sessions\` | Regenerate all session exports |
| \`super_sessions_analyze\` | Per-session topic extraction (cheap model) |
| \`super_sessions_synthesize\` | Cross-session synthesis (SOTA model) |

The raw \`.md\` files are the source of truth. Everything else derives from them.
They are version-controllable, grep-able, agent-ingestible, and survive format migrations.
`;

// ─── Entry Point ──────────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  // ─── Command: /super_sessions ───────────────────────────────────────────────

  pi.registerCommand("super_sessions", {
    description: "Regenerate project session exports (sessions/, html/, index.md)",
    handler: async (_args, ctx) => {
      await runMechanicalExtraction(ctx);
    },
  });

  // ─── Tool: super_sessions_analyze ───────────────────────────────────────────
  // LLM-callable. Returns a structured task: which sessions to analyze and how.
  // The agent (me) reads session files, calls the model, and writes analyses.

  pi.registerTool({
    name: "super_sessions_analyze",
    label: "Super Sessions Analyze",
    description:
      "Prepare topic-specific analysis of session .md files. " +
      "Returns session paths and extraction instructions. " +
      "The agent reads each session, extracts observations, and writes analyses/{topic}/{session}.md. " +
      "Skips sessions already analyzed for this topic (idempotent).",
    promptSnippet: "Analyze sessions by topic (cheap model recommended)",
    promptGuidelines: [
      "Use super_sessions_analyze to extract topic-specific observations from sessions. " +
      "Run /super_sessions first if sessions haven't been exported yet. " +
      "After calling this tool, read each session file and write analysis to the destination path.",
    ],
    parameters: Type.Object({
      topic: Type.String({
        description:
          "Topic to extract, e.g. 'engineering_decisions', 'negotiation', 'architecture', 'debugging_patterns'",
      }),
      sessionGlob: Type.Optional(
        Type.String({
          description:
            "Glob to filter sessions, e.g. '2026-06-*' or 'all'. Defaults to 'all'.",
        }),
      ),
      focusPrompt: Type.Optional(
        Type.String({
          description:
            "Additional extraction guidance, e.g. 'Focus on database schema decisions only'",
        }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const cwd = ctx.cwd;
      const sessionsDir = getSessionsDir(cwd);
      const analysesDir = path.join(getAnalysesDir(cwd), params.topic);
      const glob = params.sessionGlob || "all";

      if (!fs.existsSync(sessionsDir)) {
        return {
          content: [
            {
              type: "text",
              text: `No sessions directory found at ${sessionsDir}. Run /super_sessions first to export sessions.`,
            },
          ],
          details: {},
        };
      }

      const sessionFiles = fs
        .readdirSync(sessionsDir)
        .filter((f) => f.endsWith(".md") && !f.endsWith("_full.md"))
        .sort();

      if (sessionFiles.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `No session .md files found in ${sessionsDir}. Run /super_sessions first.`,
            },
          ],
          details: {},
        };
      }

      const matched = sessionFiles.filter((f) => {
        if (glob === "all") return true;
        const globRe = new RegExp("^" + glob.replace(/\*/g, ".*") + ".*\\.md$");
        return globRe.test(f);
      });

      if (matched.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `No sessions matched glob "${glob}". Available: ${sessionFiles.join(", ")}`,
            },
          ],
          details: {},
        };
      }

      fs.mkdirSync(analysesDir, { recursive: true });
      const toAnalyze: string[] = [];
      let skipped = 0;

      for (const file of matched) {
        const analysisPath = path.join(analysesDir, file);
        if (fs.existsSync(analysisPath)) {
          skipped++;
        } else {
          toAnalyze.push(file);
        }
      }

      if (toAnalyze.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `All ${matched.length} sessions already analyzed for topic "${params.topic}". Use --force to regenerate.`,
            },
          ],
          details: { topic: params.topic, total: matched.length, skipped },
        };
      }

      const sessionPaths = toAnalyze.map((f) => ({
        file: f,
        sourcePath: path.join(sessionsDir, f),
        analysisDest: path.join(analysesDir, f),
      }));

      const instructions = [
        `# Analyze Sessions — Topic: "${params.topic}"`,
        "",
        `**Sessions to analyze:** ${toAnalyze.length} (${skipped} already done, skipped)`,
        params.focusPrompt ? `**Focus:** ${params.focusPrompt}` : "",
        "",
        "## Instructions",
        "",
        `For each session below, read the clean .md file and extract observations about **${params.topic}**. Write each analysis to the specified destination.`,
        "",
        "For each observation include:",
        "- **Context:** what was being discussed",
        "- **Observation:** the specific insight, decision, or pattern",
        "- **Evidence:** relevant quote or paraphrase",
        "- **Significance:** why this matters to the project",
        "",
        "Use a cheap model for extraction. Format as structured markdown.",
        "",
        "## Sessions",
        "",
        ...sessionPaths.map(
          (s, i) =>
            `${i + 1}. **${s.file}** → read \`${s.sourcePath}\`, write to \`${s.analysisDest}\``,
        ),
      ].filter(Boolean).join("\n");

      return {
        content: [{ type: "text", text: instructions }],
        details: {
          topic: params.topic,
          toAnalyze: toAnalyze.length,
          skipped,
          sessionPaths,
          analysesDir,
        },
      };
    },
  });

  // ─── Tool: super_sessions_synthesize ────────────────────────────────────────

  pi.registerTool({
    name: "super_sessions_synthesize",
    label: "Super Sessions Synthesize",
    description:
      "Synthesize per-session analyses into a coherent blueprint. " +
      "Reads all analyses/{topic}/*.md, provides them as context for synthesis. " +
      "The agent writes the result to wisdom/{topic}.md.",
    promptSnippet: "Synthesize session analyses into a blueprint/document",
    promptGuidelines: [
      "Use super_sessions_synthesize after super_sessions_analyze to produce cross-session wisdom. " +
      "Reads all per-session analyses for a topic and provides synthesis instructions. " +
      "Write the synthesis document to wisdom/{topic}.md.",
    ],
    parameters: Type.Object({
      topic: Type.String({
        description: "Topic to synthesize, same as used in super_sessions_analyze",
      }),
      outputFormat: Type.Optional(
        Type.String({
          description:
            "Output format: 'blueprint' (default), 'summary', or 'timeline'",
        }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const cwd = ctx.cwd;
      const analysesDir = path.join(getAnalysesDir(cwd), params.topic);
      const wisdomDir = getWisdomDir(cwd);
      const format = params.outputFormat || "blueprint";

      if (!fs.existsSync(analysesDir)) {
        return {
          content: [
            {
              type: "text",
              text: `No analyses found for topic "${params.topic}" at ${analysesDir}. Run super_sessions_analyze first.`,
            },
          ],
          details: {},
        };
      }

      const analysisFiles = fs
        .readdirSync(analysesDir)
        .filter((f) => f.endsWith(".md"))
        .sort();

      if (analysisFiles.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `No analysis files found in ${analysesDir}.`,
            },
          ],
          details: {},
        };
      }

      // Read all analyses
      const analyses: { file: string; content: string }[] = [];
      for (const file of analysisFiles) {
        const content = fs.readFileSync(path.join(analysesDir, file), "utf-8");
        analyses.push({ file, content });
      }

      // Read index for timeline context
      let indexContent = "";
      const indexPath = path.join(getInsightsRoot(cwd), "index.md");
      if (fs.existsSync(indexPath)) {
        indexContent = fs.readFileSync(indexPath, "utf-8");
      }

      fs.mkdirSync(wisdomDir, { recursive: true });

      const instructions = [
        `# Synthesize — Topic: "${params.topic}"`,
        "",
        `**Format:** ${format}`,
        `**Sources:** ${analyses.length} analysis files`,
        `**Output:** \`${path.join(wisdomDir, `${params.topic}.md`)}\``,
        "",
        "## Instructions",
        "",
        `Synthesize the per-session analyses below into a coherent **${format}** about **${params.topic}**. Use a SOTA model.`,
        "",
        "The synthesis should:",
        "1. Identify patterns and recurring themes across sessions",
        "2. Track evolution of decisions over time",
        "3. Note contradictions or unresolved tensions",
        "4. Highlight key decisions with session context",
        "5. Provide actionable next steps",
        "",
        "## Session Timeline",
        "",
        indexContent.slice(0, 2000) || "(no index available)",
        "",
        "## Per-Session Analyses",
        "",
        ...analyses.map(
          (a, i) => `### ${i + 1}. ${a.file}\n\n${a.content}`,
        ),
      ].join("\n");

      return {
        content: [{ type: "text", text: instructions }],
        details: {
          topic: params.topic,
          format,
          sourceCount: analyses.length,
          wisdomPath: path.join(wisdomDir, `${params.topic}.md`),
        },
      };
    },
  });

  // ─── Lifecycle ──────────────────────────────────────────────────────────────

  pi.on("session_start", async (_event, ctx) => {
    const sessionsDir = getSessionsDir(ctx.cwd);
    if (fs.existsSync(sessionsDir)) {
      const count = fs
        .readdirSync(sessionsDir)
        .filter((f) => f.endsWith(".md") && !f.endsWith("_full.md")).length;
      if (count > 0) {
        ctx.ui.setStatus("super-sessions", `${count} sessions available`);
      }
    }
  });
}
