/**
 * super_sessions — Project Memory Foundation for pi
 *
 * Three-tier architecture:
 * 1. Mechanical: /super_sessions → .md + HTML (zero LLM cost)
 * 2. Analysis: super_sessions_analyze tool → per-session topic extraction (cheap model)
 * 3. Synthesis: super_sessions_synthesize tool → cross-session blueprint (SOTA model)
 */

import type { ExtensionAPI, ExtensionCommandContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import * as fs from "node:fs";
import * as path from "node:path";
import { extractSessionFile, buildIndex, listSessions, parseSessionFrontmatter, type SessionMeta, type SessionFrontmatter } from "./extraction";
import { generateSessionHtml, generateIndexHtml } from "./html-generator";
import { handleTagCommand } from "./tagging";
import { analyzeOneSession } from "./analysis";
import { runSynthesis } from "./synthesis";

// ─── Constants ────────────────────────────────────────────────────────────────────

const INSIGHTS_DIR = "project_insights";
const SESSIONS_DIR = "sessions";
const HTML_DIR = "html";
const ANALYSES_DIR = "analyses";
const WISDOM_DIR = "wisdom";

// ─── Helpers ──────────────────────────────────────────────────────────────────────

function getInsightsRoot(cwd: string): string {
  return path.join(cwd, INSIGHTS_DIR);
}

function getSessionsDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), SESSIONS_DIR);
}

function getHtmlDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), HTML_DIR);
}

function getAnalysesDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), ANALYSES_DIR);
}

function getWisdomDir(cwd: string): string {
  return path.join(getInsightsRoot(cwd), WISDOM_DIR);
}

// ─── Mechanical Extraction Command ────────────────────────────────────────────────

async function runMechanicalExtraction(ctx: ExtensionCommandContext): Promise<{
  sessions: SessionMeta[];
  count: number;
}> {
  const cwd = ctx.cwd;

  // Discover sessions via filesystem
  const sessionInfos = listSessions(cwd);
  if (sessionInfos.length === 0) {
    ctx.ui.notify("No sessions found for this project.", "warning");
    return { sessions: [], count: 0 };
  }

  const sessionsDir = getSessionsDir(cwd);
  const htmlDir = getHtmlDir(cwd);

  // Ensure output directories
  fs.mkdirSync(sessionsDir, { recursive: true });
  fs.mkdirSync(htmlDir, { recursive: true });

  const sessions: SessionMeta[] = [];
  let extracted = 0;
  let failed = 0;

  ctx.ui.notify(`Found ${sessionInfos.length} sessions. Extracting...`, "info");

  for (let i = 0; i < sessionInfos.length; i++) {
    const info = sessionInfos[i];
    const fileName = path.basename(info.path);
    ctx.ui.notify(`Extracting ${i + 1}/${sessionInfos.length}: ${fileName}...`, "info");

    try {
      const meta = extractSessionFile(info.path, sessionsDir, info);
      if (meta) {
        sessions.push(meta);
        generateSessionHtml(info.path, meta, htmlDir);
        extracted++;
      } else {
        failed++;
        console.warn(`[super_sessions] Skipped ${fileName} (no extractable content)`);
      }
    } catch (err) {
      failed++;
      console.error(`[super_sessions] Extraction error for ${fileName}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // Build index
  if (sessions.length > 0) {
    buildIndex(sessions, getInsightsRoot(cwd));
    generateIndexHtml(sessions, htmlDir);
  }

  // Write README once
  const readmePath = path.join(getInsightsRoot(cwd), "README.md");
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(readmePath, README_CONTENT, "utf-8");
  }

  ctx.ui.notify(
    `✅ Generated ${extracted} session exports to ${INSIGHTS_DIR}/ (${failed} failed)`,
    "info",
  );

  return { sessions, count: extracted };
}

// ─── README Template ─────────────────────────────────────────────────────────────

const README_CONTENT = `# Project Insights

Generated by **super_sessions** — a project memory foundation for pi.

## Directory Layout

\`\`\`
project_insights/
├── README.md          ← this file
├── index.md           ← session manifest (dates, counts, names)
├── sessions/          ← canonical source of truth
│   ├── YYYY-MM-DD_id.md       ← clean (user + assistant text)
│   └── YYYY-MM-DD_id_full.md  ← full (includes thinking, tool calls)
├── html/              ← visual browser (open index.html)
├── analyses/          ← per-session LLM extractions (by topic)
└── wisdom/            ← cross-session synthesis blueprints
\`\`\`

## How to Use

1. **Browse sessions** — Open \`html/index.html\` in any browser. No server required.
2. **Analyze by topic** — Have your agent run \`super_sessions_analyze\` with a topic.
3. **Synthesize wisdom** — Have your agent run \`super_sessions_synthesize\` to build blueprints.

## Commands & Tools

| Command/Tool | What it does |
|-------------|-------------|
| \`/super_sessions\` | Regenerate all session exports |
| \`super_sessions_analyze\` | Per-session topic extraction (cheap model) |
| \`super_sessions_synthesize\` | Cross-session synthesis (SOTA model) |

The raw \`.md\` files are the source of truth. Everything else derives from them.
They are version-controllable, grep-able, agent-ingestible, and survive format migrations.
`;

// ─── Entry Point ──────────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
  // ─── Command: /super_sessions ───────────────────────────────────────────────

  pi.registerCommand("super_sessions", {
    description: "Regenerate project session exports (sessions/, html/, index.md)",
    handler: async (_args, ctx) => {
      await runMechanicalExtraction(ctx);
    },
  });

  // ─── Subcommand: /super_sessions tag ────────────────────────────────────────

  pi.registerCommand("super_sessions tag", {
    description:
      "Tag untagged session .md files with YAML frontmatter (project_relevant, topics, summary). " +
      "Uses cheap LLM (deepseek-v4-flash). Skips already-tagged files. " +
      "Flags: --force to retag, --strip-noise to remove tangents from body.",
    handler: async (args, ctx) => {
      const force = args.includes("--force");
      const stripNoise = args.includes("--strip-noise");
      await handleTagCommand(args, ctx, { force, stripNoise });
    },
  });

  pi.registerCommand("super_sessions retag", {
    description:
      "Alias for 'tag'. Tags only sessions missing frontmatter (same as 'tag' with no --force).",
    handler: async (args, ctx) => {
      const stripNoise = args.includes("--strip-noise");
      await handleTagCommand(args, ctx, { force: false, stripNoise });
    },
  });

  // ─── Tool: super_sessions_analyze ───────────────────────────────────────────
  // LLM-callable. Calls a cheap LLM directly for each unmatched session,
  // writes structured analysis files to analyses/{topic}/{session}.md,
  // and returns a summary with counts.

  pi.registerTool({
    name: "super_sessions_analyze",
    label: "Super Sessions Analyze",
    description:
      "Extract topic-specific observations from session .md files using a cheap LLM. " +
      "For each unmatched session, reads the .md file, calls deepseek-v4-flash with a " +
      "topic-specific extraction prompt, and writes structured analysis to analyses/{topic}/{session}.md. " +
      "Skips sessions already analyzed for this topic (idempotent). " +
      "Returns a summary with analyzed, skipped (already done), skipped (not relevant), and skipped (topic mismatch) counts.",
    promptSnippet: "Analyze sessions by topic (cheap model recommended)",
    promptGuidelines: [
      "Use super_sessions_analyze to extract topic-specific observations from sessions. " +
      "It calls a cheap LLM directly per session and writes analysis files automatically. " +
      "Run /super_sessions first if sessions haven't been exported yet.",
    ],
    parameters: Type.Object({
      topic: Type.String({
        description:
          "Topic to extract, e.g. 'engineering', 'meaning', 'ideas', 'engineering_decisions', 'negotiation', 'architecture'. " +
          "Topic influences which extraction prompt template is used: 'engineering' uses analyze-engineering.md, " +
          "'meaning' uses analyze-meaning.md, 'ideas' uses analyze-ideas.md. Others use a generic fallback.",
      }),
      sessionGlob: Type.Optional(
        Type.String({
          description:
            "Glob to filter sessions, e.g. '2026-06-*' or 'all'. Defaults to 'all'.",
        }),
      ),
      focusPrompt: Type.Optional(
        Type.String({
          description:
            "Additional extraction guidance appended to the prompt, e.g. 'Focus on database schema decisions only'",
        }),
      ),
      topics: Type.Optional(
        Type.Array(Type.String(), {
          description:
            "Optional filter: only include sessions whose frontmatter topics overlap with this list. " +
            "E.g. ['architecture', 'authentication'] includes sessions tagged with any of these topics. " +
            "If omitted, all project-relevant sessions are included.",
        }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const cwd = ctx.cwd;
      const sessionsDir = getSessionsDir(cwd);
      const analysesDir = path.join(getAnalysesDir(cwd), params.topic);
      const glob = params.sessionGlob || "all";
      const topicFilter = params.topics;

      if (!fs.existsSync(sessionsDir)) {
        return {
          content: [
            {
              type: "text",
              text: `No sessions directory found at ${sessionsDir}. Run /super_sessions first to export sessions.`,
            },
          ],
          details: {},
        };
      }

      const sessionFiles = fs
        .readdirSync(sessionsDir)
        .filter((f) => f.endsWith(".md") && !f.endsWith("_full.md"))
        .sort();

      if (sessionFiles.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `No session .md files found in ${sessionsDir}. Run /super_sessions first.`,
            },
          ],
          details: {},
        };
      }

      // Match sessions by glob
      const matched = sessionFiles.filter((f) => {
        if (glob === "all") return true;
        const globRe = new RegExp("^" + glob.replace(/\*/g, ".*") + ".*\\.md$");
        return globRe.test(f);
      });

      if (matched.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `No sessions matched glob "${glob}". Available: ${sessionFiles.join(", ")}`,
            },
          ],
          details: {},
        };
      }

      // Filter by frontmatter
      const relevant: string[] = [];
      const notRelevant: string[] = [];
      const topicMismatch: string[] = [];

      for (const file of matched) {
        const sessionPath = path.join(sessionsDir, file);
        const fm = parseSessionFrontmatter(sessionPath);

        if (!fm.project_relevant) {
          notRelevant.push(file);
          continue;
        }

        if (topicFilter && topicFilter.length > 0) {
          const hasTopic = topicFilter.some((t) =>
            fm.topics.some((st) => st.toLowerCase() === t.toLowerCase()),
          );
          if (!hasTopic) {
            topicMismatch.push(file);
            continue;
          }
        }

        relevant.push(file);
      }

      if (relevant.length === 0) {
        const parts: string[] = ["No sessions available for analysis"];
        if (notRelevant.length > 0) {
          parts.push(`${notRelevant.length} filtered out (not project relevant)`);
        }
        if (topicMismatch.length > 0) {
          parts.push(`${topicMismatch.length} filtered out (topic mismatch)`);
        }
        return {
          content: [{ type: "text", text: parts.join(". ") + "." }],
          details: { topic: params.topic, matched: matched.length, notRelevant: notRelevant.length, topicMismatch: topicMismatch.length },
        };
      }

      fs.mkdirSync(analysesDir, { recursive: true });

      // Check which already have analyses (idempotent)
      const toAnalyze: string[] = [];
      let alreadyAnalyzed = 0;

      for (const file of relevant) {
        const analysisPath = path.join(analysesDir, file);
        if (fs.existsSync(analysisPath)) {
          alreadyAnalyzed++;
        } else {
          toAnalyze.push(file);
        }
      }

      if (toAnalyze.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: [
                `All ${relevant.length} relevant sessions already analyzed for topic "${params.topic}".`,
                alreadyAnalyzed > 0 ? `${alreadyAnalyzed} already analyzed.` : "",
                notRelevant.length > 0 ? `${notRelevant.length} skipped (not project relevant).` : "",
                topicMismatch.length > 0 ? `${topicMismatch.length} skipped (topic mismatch).` : "",
              ].filter(Boolean).join(" "),
            },
          ],
          details: {
            topic: params.topic,
            total: relevant.length,
            alreadyAnalyzed,
            notRelevant: notRelevant.length,
            topicMismatch: topicMismatch.length,
          },
        };
      }

      // Analyze each session via cheap LLM
      const analyzed: string[] = [];
      const errors: string[] = [];

      for (let i = 0; i < toAnalyze.length; i++) {
        const file = toAnalyze[i];
        const sessionPath = path.join(sessionsDir, file);
        const analysisDest = path.join(analysesDir, file);

        // Report progress
        ctx.ui.notify(
          `Analyzing ${i + 1}/${toAnalyze.length}: ${file} for topic "${params.topic}"...`,
          "info",
        );

        const result = await analyzeOneSession(
          sessionPath,
          analysisDest,
          params.topic,
          ctx,
          params.focusPrompt,
        );

        if (result.success) {
          analyzed.push(file);
        } else {
          errors.push(`${file}: ${result.error}`);
          ctx.ui.notify(`⚠️ Analysis failed for ${file}: ${result.error}`, "warning");
        }
      }

      // Build summary
      const summaryParts: string[] = [];

      if (analyzed.length > 0) {
        summaryParts.push(`Analyzed ${analyzed.length} session${analyzed.length !== 1 ? "s" : ""} for topic "${params.topic}"`);
      }
      if (alreadyAnalyzed > 0) {
        summaryParts.push(`${alreadyAnalyzed} skipped (already analyzed)`);
      }
      if (notRelevant.length > 0) {
        summaryParts.push(`${notRelevant.length} skipped (not project relevant)`);
      }
      if (topicMismatch.length > 0) {
        summaryParts.push(`${topicMismatch.length} skipped (topic mismatch)`);
      }
      if (errors.length > 0) {
        summaryParts.push(`${errors.length} error${errors.length !== 1 ? "s" : ""}`);
      }
      if (topicFilter && topicFilter.length > 0) {
        summaryParts.push(`Filtered by topics: ${topicFilter.join(", ")}`);
      }

      const summary = summaryParts.join(". ") + ".";

      return {
        content: [
          {
            type: "text",
            text: [
              `## ✅ Analysis Complete — Topic: "${params.topic}"`,
              "",
              summary,
              "",
              analyzed.length > 0 ? `**Output:** ${analysesDir}` : "",
              errors.length > 0
                ? [
                    "",
                    "### Errors",
                    "",
                    ...errors.map((e) => `- ${e}`),
                    "",
                    "Error notes have been written to the analysis files.",
                  ].join("\n")
                : "",
              params.focusPrompt ? `**Focus prompt used:** ${params.focusPrompt}` : "",
            ]
              .filter(Boolean)
              .join("\n"),
          },
        ],
        details: {
          topic: params.topic,
          analyzed: analyzed.length,
          alreadyAnalyzed,
          notRelevant: notRelevant.length,
          topicMismatch: topicMismatch.length,
          errors: errors.length,
          analysesDir,
        },
      };
    },
  });

  // ─── Tool: super_sessions_synthesize ────────────────────────────────────────
  // LLM-callable. Calls a SOTA LLM directly for cross-session synthesis,
  // reads all analysis files for a topic, and writes the synthesized blueprint
  // to wisdom/{topic}.md.

  pi.registerTool({
    name: "super_sessions_synthesize",
    label: "Super Sessions Synthesize",
    description:
      "Synthesize per-session analyses into a coherent blueprint using a SOTA model. " +
      "Reads all analyses/{topic}/*.md, calls deepseek-v4-pro directly to synthesize, " +
      "and writes the result to wisdom/{topic}.md.",
    promptSnippet: "Synthesize session analyses into a blueprint/document (SOTA model)",
    promptGuidelines: [
      "Use super_sessions_synthesize after super_sessions_analyze to produce cross-session wisdom. " +
      "It calls a SOTA model (deepseek-v4-pro) directly, reads all per-session analyses, " +
      "and writes the synthesis to wisdom/{topic}.md automatically.",
    ],
    parameters: Type.Object({
      topic: Type.String({
        description: "Topic to synthesize, same as used in super_sessions_analyze",
      }),
      outputFormat: Type.Optional(
        Type.String({
          description:
            "Output format: 'blueprint' (default), 'summary', or 'timeline'",
        }),
      ),
      sessionGlob: Type.Optional(
        Type.String({
          description:
            "Glob to filter analyses by session, e.g. '2026-06-*' or 'all'. Defaults to 'all'.",
        }),
      ),
      topics: Type.Optional(
        Type.Array(Type.String(), {
          description:
            "Optional filter: only include analyses from sessions whose frontmatter topics overlap with this list. " +
            "E.g. ['architecture', 'authentication']. If omitted, all project-relevant sessions are included.",
        }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const cwd = ctx.cwd;
      const analysesDir = path.join(getAnalysesDir(cwd), params.topic);
      const sessionsDir = getSessionsDir(cwd);
      const wisdomDir = getWisdomDir(cwd);
      const format = params.outputFormat || "blueprint";
      const glob = params.sessionGlob || "all";
      const topicFilter = params.topics;

      if (!fs.existsSync(analysesDir)) {
        return {
          content: [
            {
              type: "text",
              text: `No analyses found for topic "${params.topic}" at ${analysesDir}. Run super_sessions_analyze first.`,
            },
          ],
          details: {},
        };
      }

      const analysisFiles = fs
        .readdirSync(analysesDir)
        .filter((f) => f.endsWith(".md"))
        .sort();

      if (analysisFiles.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: `No analysis files found in ${analysesDir}.`,
            },
          ],
          details: {},
        };
      }

      // Filter analyses by glob, then by frontmatter
      const filteredAnalyses: { file: string; content: string }[] = [];
      let notRelevant = 0;
      let topicMismatch = 0;
      let globSkipped = 0;

      for (const file of analysisFiles) {
        // Apply glob filter
        if (glob !== "all") {
          const globRe = new RegExp("^" + glob.replace(/\*/g, ".*") + ".*\\.md$");
          if (!globRe.test(file)) {
            globSkipped++;
            continue;
          }
        }

        // Read source session frontmatter for filtering
        const sessionPath = path.join(sessionsDir, file);
        if (fs.existsSync(sessionPath)) {
          const fm = parseSessionFrontmatter(sessionPath);

          if (!fm.project_relevant) {
            notRelevant++;
            continue;
          }

          if (topicFilter && topicFilter.length > 0) {
            const hasTopic = topicFilter.some((t) =>
              fm.topics.some((st) => st.toLowerCase() === t.toLowerCase()),
            );
            if (!hasTopic) {
              topicMismatch++;
              continue;
            }
          }
        }

        // Include this analysis
        const content = fs.readFileSync(path.join(analysesDir, file), "utf-8");
        filteredAnalyses.push({ file, content });
      }

      if (filteredAnalyses.length === 0) {
        const parts: string[] = [`No analyses available for synthesis of topic "${params.topic}".`];
        if (globSkipped > 0) parts.push(`${globSkipped} filtered out by glob.`);
        if (notRelevant > 0) parts.push(`${notRelevant} filtered out (not project relevant).`);
        if (topicMismatch > 0) parts.push(`${topicMismatch} filtered out (topic mismatch).`);
        return {
          content: [{ type: "text", text: parts.join(" ") }],
          details: { topic: params.topic, total: analysisFiles.length, globSkipped, notRelevant, topicMismatch },
        };
      }

      // Read index for session timeline context
      let indexContent = "";
      const indexPath = path.join(getInsightsRoot(cwd), "index.md");
      if (fs.existsSync(indexPath)) {
        indexContent = fs.readFileSync(indexPath, "utf-8");
      }

      // Ensure wisdom directory exists
      fs.mkdirSync(wisdomDir, { recursive: true });

      // Report synthesis in progress
      ctx.ui.notify(
        `Synthesizing ${filteredAnalyses.length} analyses for topic "${params.topic}" using SOTA model...`,
        "info",
      );

      // Call the SOTA model directly
      const result = await runSynthesis(
        {
          topic: params.topic,
          format,
          analyses: filteredAnalyses,
          indexContent,
        },
        ctx,
      );

      if (!result.success) {
        const errorMsg = result.error || "Unknown synthesis error";
        ctx.ui.notify(`⚠️ Synthesis failed: ${errorMsg}`, "warning");
        return {
          content: [
            {
              type: "text",
              text: `## ❌ Synthesis Failed — Topic: "${params.topic}"` +
                `\n\n**Model:** deepseek-v4-pro (SOTA)` +
                `\n**Sources:** ${filteredAnalyses.length} analysis files` +
                `\n**Error:** ${errorMsg}` +
                `\n\nTry again or check your model configuration.`,
            },
          ],
          details: {
            topic: params.topic,
            format,
            sourceCount: filteredAnalyses.length,
            totalAnalyses: analysisFiles.length,
            success: false,
            error: errorMsg,
          },
        };
      }

      // Write synthesized document to wisdom/{topic}.md
      const wisdomPath = path.join(wisdomDir, `${params.topic}.md`);

      const document = [
        `# ${topicToTitle(params.topic)} — ${formatToTitle(format)}`,
        ``,
        `**Topic:** ${params.topic}`,
        `**Format:** ${format}`,
        `**Generated:** ${new Date().toISOString()}`,
        `**Model:** deepseek-v4-pro (SOTA)`,
        `**Sources:** ${filteredAnalyses.length} analysis files from ${analysisFiles.length} total`,
        notRelevant > 0 ? `**Excluded (not relevant):** ${notRelevant}` : null,
        topicMismatch > 0 ? `**Excluded (topic mismatch):** ${topicMismatch}` : null,
        globSkipped > 0 ? `**Excluded (glob):** ${globSkipped}` : null,
        topicFilter && topicFilter.length > 0
          ? `**Topic filter:** ${topicFilter.join(", ")}`
          : null,
        ``,
        `---`,
        ``,
        result.content,
      ]
        .filter(Boolean)
        .join("\n");

      fs.writeFileSync(wisdomPath, document, "utf-8");

      ctx.ui.notify(
        `✅ ${formatToTitle(format)} written to ${path.relative(cwd, wisdomPath)}`,
        "info",
      );

      // Build result summary
      const summaryParts: string[] = [
        `✅ Synthesis complete!`,
        `**Topic:** ${params.topic}`,
        `**Format:** ${format}`,
        `**Model:** deepseek-v4-pro (SOTA)`,
        `**Sources:** ${filteredAnalyses.length} analysis files`,
        `**Output:** \`${path.relative(cwd, wisdomPath)}\``,
      ];
      if (globSkipped > 0) summaryParts.push(`**Excluded by glob:** ${globSkipped}`);
      if (notRelevant > 0) summaryParts.push(`**Excluded (not relevant):** ${notRelevant}`);
      if (topicMismatch > 0) summaryParts.push(`**Excluded (topic mismatch):** ${topicMismatch}`);
      if (topicFilter && topicFilter.length > 0) {
        summaryParts.push(`**Filtered by topics:** ${topicFilter.join(", ")}`);
      }

      const wordCount = result.content.split(/\s+/).filter(Boolean).length;
      summaryParts.push(`**Document size:** ~${wordCount} words`);

      return {
        content: [
          {
            type: "text",
            text: summaryParts.join("\n"),
          },
        ],
        details: {
          topic: params.topic,
          format,
          sourceCount: filteredAnalyses.length,
          totalAnalyses: analysisFiles.length,
          notRelevant,
          topicMismatch,
          globSkipped,
          success: true,
          wordCount,
          wisdomPath: path.relative(cwd, wisdomPath),
        },
      };
    },
  });

  // ─── Helpers for synthesize tool ──────────────────────────────────────────────

  function topicToTitle(topic: string): string {
    return topic
      .replace(/[-_]/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase())
      .replace(/\b(And|Of|The|In|For)\b/g, (c) => c.toLowerCase())
      .replace(/^./, (c) => c.toUpperCase());
  }

  function formatToTitle(format: string): string {
    switch (format) {
      case "blueprint":
        return "Blueprint";
      case "summary":
        return "Executive Summary";
      case "timeline":
        return "Timeline";
      default:
        return format.charAt(0).toUpperCase() + format.slice(1);
    }
  }

  // ─── Lifecycle ──────────────────────────────────────────────────────────────

  pi.on("session_start", async (_event, ctx) => {
    const sessionsDir = getSessionsDir(ctx.cwd);
    if (fs.existsSync(sessionsDir)) {
      const count = fs
        .readdirSync(sessionsDir)
        .filter((f) => f.endsWith(".md") && !f.endsWith("_full.md")).length;
      if (count > 0) {
        ctx.ui.setStatus("super-sessions", `${count} sessions available`);
      }
    }
  });
}
